CREATE TABLE BOOK (
	BCode INT AUTO_INCREMENT PRIMARY KEY,
    BName VARCHAR(25) NOT NULL,
    AName VARCHAR(25) NOT NULL
);
CREATE TABLE BookChapter(
    BCode INT NOT NULL,
    CId INT NOT NULL UNIQUE ,
    CTitle VARCHAR(25) NOT NULL,
    CContent TEXT NOT NULL,
    FOREIGN KEY (BCode) REFERENCES Book(BCode) ON DELETE CASCADE,
    PRIMARY KEY (BCode, CId) 
);